name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-20.04

    services:
      postgresql:
        image: postgres:14
        env:
          POSTGRES_DB: forge
          POSTGRES_USER: forge
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd=pg_isready --health-interval=10s --health-timeout=5s --health-retries=3

    name: PostgreSQL 14

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_pgsql
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-scripts --ignore-platform-reqs --no-progress --optimize-autoloader --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: pgsql
          DB_PASSWORD: password
